repos:
- repo: https://github.com/ambv/black
  rev: 19.3b0
  hooks:
  - id: black
    language_version: python3
- repo: https://github.com/asottile/blacken-docs
  rev: v0.5.0
  hooks:
  - id: blacken-docs
    additional_dependencies: [black==19.3b0]
- repo: https://github.com/asottile/pyupgrade
  rev: v1.17.1
  hooks:
  - id: pyupgrade
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.2.3
  hooks:
  - id: check-ast
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
  - id: mixed-line-ending
  - id: trailing-whitespace
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.7.7
  hooks:
  - id: flake8
